### ISSUE TITLE
Better support for smaller screens

### ISSUE THREAD

**Issue by tiborepcek** [arkanis/simple-chat#1]
Hi Stephan!

First of all, thank you very much for this chat. I find it really useful for quick implementing on pretty much every hosting out there nowadays.

The only thing that I am missing is better support for smaller screens (especially on mobile phones). I am not a web developer, but I found a simple solution, which you could paste to the head section. What do you think?

`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

**Comment by arkanis** [comment]
Hi tiborepcek,

good point, I didn't think about that! Version 2.0.2 (6a20049f7128b122196ce11f31731634c153fc42) fixes that.

- I've changed the viewport tag to `<meta name=viewport content="initial-scale=1.0">`. That way mobile browsers are free to use small viewport sizes if the device is actually small but has a high pixel density.
- Also added an UTF-8 encoding meta tag. Shouldn't be necessary if your webserver already says that the HTML file is UTF-8 encoded but added it in while I was at it. Maybe I can remove it in a few years once it's the default encoding everywhere.

Let me know it it's still make trouble. I don't have a lot of devices to test that.

Happy programming
Stephan
